-- Triggers

-- TRIGGER TO CHECK IF THE DRIVER IS ABOVE 18 YEARS OF AGE
CREATE OR REPLACE TRIGGER DRIVER_AGE_CHECK 
BEFORE INSERT 
    ON DD_DRIVER
    FOR EACH ROW 
DECLARE 
    AGE NUMBER; 
BEGIN
    AGE := floor(months_between( sysdate, :NEW.DATE_OF_BIRTH) /12);
    IF AGE < 18 THEN 
        RAISE_APPLICATION_ERROR(-20001, 'Driver not attained 18 years.');
    END IF; 
END;
/   



CREATE OR REPLACE TRIGGER CREDIT_CARD_EXPIRY_CHECK
BEFORE INSERT 
    ON DD_CREDITCARD
    FOR EACH ROW 
BEGIN 
    IF :NEW.EXPIRY_DATE < SYSDATE THEN 
        RAISE_APPLICATION_ERROR(-20001, 'Credit Card is expired.');
    END IF;
END;
/